name: 'slack-pr-summary'
description: 'Send summary of open PRs to Slack'
author: 'tgallacher'

inputs:
  github_token:
    description: 'Github token with access to the target repo'
    required: true
  repoOwner:
    description: 'Github repository owner from url. Format: github.com/<owner>/<name>'
    required: true
  repoName:
    description: 'Github repository name from url. Format: github.com/<owner>/<name>'
    required: true

outputs:
  prs:
    # This will be a JSON.stringified array
    description: 'List of PRItem objects found for the given repo'

runs:
  using: node20
  main: dist/index.js
