name: "slack-pr-summary"
description: "Send summary of open PRs to Slack"
author: "tgallacher"

inputs:
  github_token:
    description: "Github token with access to the target repo"
    required: true
  repo:
    description: "Github repository url, format: github.com/<owner>/<name>"
    required: true
  msg_header:
    description: "Provide text to show at the top of the summary"
    required: true
  slack_webhook_url:
    description: "Your configured Slack Incoming webhook"
    required: true

runs:
  using: node20
  main: dist/index.js
